### ISSUE TITLE
Short how-to guides

### ISSUE THREAD

**Issue by ashwinvis** [snek5000/snek5000#142]
I try to collect various questions we have asked ourselves. It doesn't have to be a long tutorial, but a short answer with a code snippet, linking to other pages in the docs when necessary.

Something similar to https://docs.pytest.org/en/7.1.x/how-to/index.html

# How-to guides

## User perspective

- [x] Restart simulation (link towards a specific section in tgv tutorial - to be written -)
- [x] Suppress Fortran warnings during compilation
- [ ] Error if Fortran warnings are raised from the user file
- [ ] Set adaptive time step (explanation + link towards tgv tutorial)
- [ ] Read the log file and check for errors
- [x] Run the simulation in the foreground (explanation + link towards phill tutorial)
- [ ] Configure different C and Fortran compilers for compilation (link towards first tutorial)
- [x] Export a standalone source code archive which excludes `snek5000`
- [x] Make an compressed archive of simulation data
- [x] Read from / write to `*.par` files
- [x] Load/plot/movie hexa file (add a specific section in phill tutorial, improve https://snek5000.readthedocs.io/en/latest/_generated/snek5000.output.phys_fields.html)
- [x]  Load/plot/movie hexa file stat (see #152)
- [x] Load/plot print_stdout functions (add a specific section in one of the tutorial) (see https://snek5000.readthedocs.io/en/latest/_generated/snek5000.output.print_stdout.html)
- [x] Load/plot files with `sim.output.phys_fields` readers (`ReaderPymech` and `ReaderPymechStats`, see #151) + mention in phill tutorial why this cannot be used...
- [x] Load/plot history points (cbox tutorial)
- [ ] spatial_means (see #150)
- [x] Use snakemake command line (examples are given in https://github.com/snek5000/snek5000/blob/main/src/snek5000/make.py#L84 but an example does not work for me (see https://github.com/snek5000/snek5000/issues/163#issuecomment-1305438759))

## Development of solvers

- [ ] Configure `userParams` in `*.par` file linked to Python params with human-readable names

## Development of snek5000

- [ ] Build the documentation
- [ ] Run the test suite
- [x] Make a release
- [x] How to modify the tutorials (.md files) with Jupyter

**Comment by ashwinvis** [comment]
Feel free to edit the task list and add more things you have encountered in your workflow @snek5000/cbox-dev

**Comment by ashwinvis** [comment]
I will create a blank how-to page with appropriate sections

**Comment by ashwinvis** [comment]
How to save the first field file of the simulation / initial condition. 

One needs to add this to end of `userchk` subroutine:


## If KTH framework is not used

```fortran

      if (istep .eq. 0)
         ! first timestep
         call outpost(vx, vy, vz, pr, t, '   ')  ! write initial condition
      endif
```

## If KTH framework is used

```fortran

      ! finalise framework
      if (ISTEP.eq.NSTEPS.or.LASTEP.eq.1) then
         call frame_end
      else if (istep .eq. 0 .and. (.not. chpt_ifrst)) then
         ! first timestep which is not restarted
         call outpost(vx, vy, vz, pr, t, '   ')  ! write initial condition
      endif
```

**Comment by paugier** [comment]
With cbox (using KTH framework), I get 

```
   95 |       else if (istep .eq. 0 .and. (.not. chpt_ifrst)) then
      |                                        1
Error: Operand of .not. operator at (1) is REAL(8)
```

**Comment by paugier** [comment]
I tried 

```
else if (istep .eq. 0 .and. (chpt_ifrst == 0) ) then
```

https://github.com/snek5000/snek5000-cbox/pull/42

**Comment by ashwinvis** [comment]
That's very strange. For it is a logical variable.

https://github.com/KTH-Nek5000/KTH_Toolbox/blob/4e12dbccfc48ffb5b3991f354c7200c628694418/io/checkpoint/CHKPOINTD#L23

**Comment by paugier** [comment]
We are now nearly ready to release snek5000 0.8.0 (and then to communicate on the project and send the link towards the doc). It would be nice if more how to pages would be written. @ashwinvis do you think you could work on few of these pages in a dedicated PR?

**Comment by ashwinvis** [comment]
I understand that it is nice to have a release with good docs. If we do so it might delay the release by ~1 week. Is that alright?

**Comment by paugier** [comment]
I just released fluidsim 0.7.1 so snek5000 0.8.0 is really nearly ready! But it is reasonable to wait few days more to polish a bit the documentation. I think beginning of next week (5 or 6 Dec.) could be nice!

**Comment by paugier** [comment]
I've just created many small and more manageable issues so we can finally close this one!
